version: '3.9'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ./src:/home/node/app
    ports:
      - "3000:3000"
    command: npm run dev